In [1]:
import pandas as pd

In [2]:
prefix = 'https://github.com/DataTalksClub/nyc-tlc-data/releases/download/yellow/'
df = pd.read_csv(prefix + '/yellow_tripdata_2021-01.csv.gz')

/tmp/ipykernel_5837/2955732618.py:2: DtypeWarning: Columns (6) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(prefix + '/yellow_tripdata_2021-01.csv.gz')

In [3]:
df .head()

,VendorID,tpep_pickup_datetime,tpep_dropoff_datetime,passenger_count,trip_distance,RatecodeID,store_and_fwd_flag,PULocationID,DOLocationID,payment_type,fare_amount,extra,mta_tax,tip_amount,tolls_amount,improvement_surcharge,total_amount,congestion_surcharge
0,1.0,2021-01-01 00:30:10,2021-01-01 00:36:12,1.0,2.10,1.0,N,142,43,2.0,8.0,3.0,0.5,0.00,0.0,0.3,11.80,2.5
1,1.0,2021-01-01 00:51:20,2021-01-01 00:52:19,1.0,0.20,1.0,N,238,151,2.0,3.0,0.5,0.5,0.00,0.0,0.3,4.30,0.0
2,1.0,2021-01-01 00:43:30,2021-01-01 01:11:06,1.0,14.70,1.0,N,132,165,1.0,42.0,0.5,0.5,8.65,0.0,0.3,51.95,0.0
3,1.0,2021-01-01 00:15:48,2021-01-01 00:31:01,0.0,10.60,1.0,N,138,132,1.0,29.0,0.5,0.5,6.05,0.0,0.3,36.35,0.0
4,2.0,2021-01-01 00:31:49,2021-01-01 00:48:21,1.0,4.94,1.0,N,68,33,1.0,16.5,0.5,0.5,4.06,0.0,0.3,24.36,2.5

In [4]:
df.dtypes

VendorID                 float64
tpep_pickup_datetime      object
tpep_dropoff_datetime     object
passenger_count          float64
trip_distance            float64
RatecodeID               float64
store_and_fwd_flag        object
PULocationID               int64
DOLocationID               int64
payment_type             float64
fare_amount              float64
extra                    float64
mta_tax                  float64
tip_amount               float64
tolls_amount             float64
improvement_surcharge    float64
total_amount             float64
congestion_surcharge     float64
dtype: object

In [5]:
df.shape

(1369765, 18)

In [6]:
dtype = {
    "VendorID": "Int64",
    "passenger_count": "Int64",
    "trip_distance": "float64",
    "RatecodeID": "Int64",
    "store_and_fwd_flag": "string",
    "PULocationID": "Int64",
    "DOLocationID": "Int64",
    "payment_type": "Int64",
    "fare_amount": "float64",
    "extra": "float64",
    "mta_tax": "float64",
    "tip_amount": "float64",
    "tolls_amount": "float64",
    "improvement_surcharge": "float64",
    "total_amount": "float64",
    "congestion_surcharge": "float64"
}

parse_dates = [
    "tpep_pickup_datetime",
    "tpep_dropoff_datetime"
]

df = pd.read_csv(
    prefix + '/yellow_tripdata_2021-01.csv.gz',
    dtype=dtype,
    parse_dates=parse_dates
)

In [7]:
df.dtypes

VendorID                          Int64
tpep_pickup_datetime     datetime64[ns]
tpep_dropoff_datetime    datetime64[ns]
passenger_count                   Int64
trip_distance                   float64
RatecodeID                        Int64
store_and_fwd_flag       string[python]
PULocationID                      Int64
DOLocationID                      Int64
payment_type                      Int64
fare_amount                     float64
extra                           float64
mta_tax                         float64
tip_amount                      float64
tolls_amount                    float64
improvement_surcharge           float64
total_amount                    float64
congestion_surcharge            float64
dtype: object

In [8]:
df. head()

,VendorID,tpep_pickup_datetime,tpep_dropoff_datetime,passenger_count,trip_distance,RatecodeID,store_and_fwd_flag,PULocationID,DOLocationID,payment_type,fare_amount,extra,mta_tax,tip_amount,tolls_amount,improvement_surcharge,total_amount,congestion_surcharge
0,1,2021-01-01 00:30:10,2021-01-01 00:36:12,1,2.10,1,N,142,43,2,8.0,3.0,0.5,0.00,0.0,0.3,11.80,2.5
1,1,2021-01-01 00:51:20,2021-01-01 00:52:19,1,0.20,1,N,238,151,2,3.0,0.5,0.5,0.00,0.0,0.3,4.30,0.0
2,1,2021-01-01 00:43:30,2021-01-01 01:11:06,1,14.70,1,N,132,165,1,42.0,0.5,0.5,8.65,0.0,0.3,51.95,0.0
3,1,2021-01-01 00:15:48,2021-01-01 00:31:01,0,10.60,1,N,138,132,1,29.0,0.5,0.5,6.05,0.0,0.3,36.35,0.0
4,2,2021-01-01 00:31:49,2021-01-01 00:48:21,1,4.94,1,N,68,33,1,16.5,0.5,0.5,4.06,0.0,0.3,24.36,2.5

In [9]:
df ["tpep_pickup_datetime"]

0         2021-01-01 00:30:10
1         2021-01-01 00:51:20
2         2021-01-01 00:43:30
3         2021-01-01 00:15:48
4         2021-01-01 00:31:49
                  ...
1369760   2021-01-25 08:32:04
1369761   2021-01-25 08:34:00
1369762   2021-01-25 08:37:00
1369763   2021-01-25 08:28:00
1369764   2021-01-25 08:38:00
Name: tpep_pickup_datetime, Length: 1369765, dtype: datetime64[ns]

In [10]:
from sqlalchemy import create_engine

In [11]:
engine = create_engine('postgresql://root:root@localhost:5432/ny_taxi')

In [12]:
df.head(0).to_sql ( name='yellow_taxi_data', con=engine ,if_exists='replace')

0

In [13]:
print(pd.io.sql.get_schema(df, name='yellow_taxi_data', con=engine))

CREATE TABLE yellow_taxi_data (
	"VendorID" BIGINT,
	tpep_pickup_datetime TIMESTAMP WITHOUT TIME ZONE,
	tpep_dropoff_datetime TIMESTAMP WITHOUT TIME ZONE,
	passenger_count BIGINT,
	trip_distance FLOAT(53),
	"RatecodeID" BIGINT,
	store_and_fwd_flag TEXT,
	"PULocationID" BIGINT,
	"DOLocationID" BIGINT,
	payment_type BIGINT,
	fare_amount FLOAT(53),
	extra FLOAT(53),
	mta_tax FLOAT(53),
	tip_amount FLOAT(53),
	tolls_amount FLOAT(53),
	improvement_surcharge FLOAT(53),
	total_amount FLOAT(53),
	congestion_surcharge FLOAT(53)
)

In [14]:
pd.read_sql("SELECT * FROM yellow_taxi_data LIMIT 5", con=engine)

Empty DataFrame
Columns: [index, VendorID, tpep_pickup_datetime, tpep_dropoff_datetime, passenger_count, trip_distance, RatecodeID, store_and_fwd_flag, PULocationID, DOLocationID, payment_type, fare_amount, extra, mta_tax, tip_amount, tolls_amount, improvement_surcharge, total_amount, congestion_surcharge]
Index: []

In [15]:
len(df)

1369765

In [16]:
df_iter = pd.read_csv(prefix + '/yellow_tripdata_2021-01.csv.gz' ,iterator=True,
    chunksize=100000)

In [17]:
!uv add tqdm

Resolved 120 packages in 0.58ms
Audited 12 packages in 0.16ms

In [18]:
from tqdm.auto import tqdm

In [19]:
for df_chunk in tqdm(df_iter):
    df_chunk.to_sql ( name='yellow_taxi_data', con=engine ,if_exists='append')

0it [00:00, ?it/s]

/workspaces/data_pipeline/pipeline/.venv/lib/python3.13/site-packages/tqdm/std.py:1181: DtypeWarning: Columns (6) have mixed types. Specify dtype option on import or set low_memory=False.
  for obj in iterable:

In [43]:
url = 'https://github.com/DataTalksClub/nyc-tlc-data/releases/download/misc/taxi_zone_lookup.csv'

In [44]:
df_zones = pd.read_csv(url)

In [45]:
 df_zones.to_sql ( name='zones', con=engine ,if_exists='replace')

265

In [46]:

url = 'https://d37ci6vzurychx.cloudfront.net/trip-data/green_tripdata_2025-11.parquet'
df = pd.read_parquet(url)

print(df.head(15))

    VendorID lpep_pickup_datetime lpep_dropoff_datetime store_and_fwd_flag  \
0          2  2025-11-01 00:34:48   2025-11-01 00:41:39                  N
1          2  2025-11-01 00:18:52   2025-11-01 00:24:27                  N
2          2  2025-11-01 01:03:14   2025-11-01 01:15:24                  N
3          2  2025-11-01 00:10:57   2025-11-01 00:24:53                  N
4          1  2025-11-01 00:03:48   2025-11-01 00:19:38                  N
5          1  2025-11-01 00:42:13   2025-11-01 01:04:50                  N
6          2  2025-11-01 00:05:41   2025-11-01 00:39:20                  N
7          2  2025-11-01 00:42:14   2025-11-01 01:13:20                  N
8          2  2025-11-01 00:03:08   2025-11-01 00:06:27                  N
9          2  2025-11-01 00:56:33   2025-11-01 01:01:34                  N
10         2  2025-10-31 23:55:08   2025-11-01 00:25:30                  N
11         2  2025-11-01 00:02:26   2025-11-01 00:02:31                  N
12         2  2025-11-01 00:38:07   2025-11-01 00:44:51                  N
13         2  2025-11-01 00:18:46   2025-11-01 00:30:40                  N
14         2  2025-11-01 00:05:40   2025-11-01 00:05:45                  N

    RatecodeID  PULocationID  DOLocationID  passenger_count  trip_distance  \
0          1.0            74            42              1.0           0.74
1          1.0            74            42              2.0           0.95
2          1.0            83           160              1.0           2.19
3          1.0           166           127              1.0           5.44
4          1.0           166           262              1.0           3.20
5          1.0           112            48              2.0           5.10
6          1.0            83            87              1.0           9.80
7          1.0            66           233              1.0           5.01
8          1.0           223           223              1.0           0.63
9          1.0           130           130              1.0           1.15
10         1.0            41           234              1.0           5.30
11         5.0            93            93              1.0           0.00
12         5.0            92           192              2.0           1.13
13         1.0           243           152              1.0           3.73
14         5.0           244           244              1.0           0.00

    fare_amount  ...  mta_tax  tip_amount  tolls_amount  ehail_fee  \
0           7.2  ...      0.5        1.94           0.0        NaN
1           7.2  ...      0.5        0.00           0.0        NaN
2          13.5  ...      0.5        5.00           0.0        NaN
3          24.7  ...      0.5        0.50           0.0        NaN
4          18.4  ...      1.5        1.00           0.0        NaN
5          26.8  ...      1.5        6.55           0.0        NaN
6          43.6  ...      0.5        9.92           0.0        NaN
7          28.9  ...      0.5        6.98           0.0        NaN
8           5.1  ...      0.5        1.52           0.0        NaN
9           7.9  ...      0.5        0.00           0.0        NaN
10         31.7  ...      0.5        4.00           0.0        NaN
11         28.0  ...      0.0        5.80           0.0        NaN
12         15.0  ...      0.0        0.00           0.0        NaN
13         18.4  ...      0.5        4.18           0.0        NaN
14          9.5  ...      0.0        2.10           0.0        NaN

    improvement_surcharge  total_amount  payment_type  trip_type  \
0                     1.0         11.64           1.0        1.0
1                     1.0          9.70           2.0        1.0
2                     1.0         21.00           1.0        1.0
3                     1.0         27.70           1.0        1.0
4                     1.0         24.65           1.0        1.0
5                     1.0         39.35           1.0        1.0
6                     1.0         59.52           1.0        1.0
7                     1.0         41.88           1.0        1.0
8                     1.0          9.12           1.0        1.0
9                     1.0         10.40           2.0        1.0
10                    1.0         41.70           1.0        1.0
11                    1.0         34.80           1.0        2.0
12                    1.0         16.00           1.0        2.0
13                    1.0         25.08           1.0        1.0
14                    1.0         12.60           1.0        2.0

    congestion_surcharge  cbd_congestion_fee
0                   0.00                0.00
1                   0.00                0.00
2                   0.00                0.00
3                   0.00                0.00
4                   2.75                0.00
5                   2.75                0.75
6                   2.75                0.75
7                   2.75                0.75
8                   0.00                0.00
9                   0.00                0.00
10                  2.75                0.75
11                  0.00                0.00
12                  0.00                0.00
13                  0.00                0.00
14                  0.00                0.00

[15 rows x 21 columns]

In [42]:
df .info

<bound method DataFrame.info of        VendorID lpep_pickup_datetime lpep_dropoff_datetime store_and_fwd_flag  \
0             2  2025-11-01 00:34:48   2025-11-01 00:41:39                  N
1             2  2025-11-01 00:18:52   2025-11-01 00:24:27                  N
2             2  2025-11-01 01:03:14   2025-11-01 01:15:24                  N
3             2  2025-11-01 00:10:57   2025-11-01 00:24:53                  N
4             1  2025-11-01 00:03:48   2025-11-01 00:19:38                  N
...         ...                  ...                   ...                ...
46907         2  2025-11-30 19:58:34   2025-11-30 20:14:28               None
46908         2  2025-11-30 19:34:00   2025-11-30 19:46:00               None
46909         2  2025-11-30 21:46:46   2025-11-30 22:17:55               None
46910         2  2025-11-30 21:00:00   2025-11-30 21:15:00               None
46911         2  2025-11-30 23:26:00   2025-11-30 23:42:00               None

       RatecodeID  PULocationID  DOLocationID  passenger_count  trip_distance  \
0             1.0            74            42              1.0           0.74
1             1.0            74            42              2.0           0.95
2             1.0            83           160              1.0           2.19
3             1.0           166           127              1.0           5.44
4             1.0           166           262              1.0           3.20
...           ...           ...           ...              ...            ...
46907         NaN            59            51              NaN           8.50
46908         NaN            74           151              NaN           1.73
46909         NaN            33           163              NaN           7.52
46910         NaN            16            95              NaN           5.61
46911         NaN            65            87              NaN           2.91

       fare_amount  ...  mta_tax  tip_amount  tolls_amount  ehail_fee  \
0             7.20  ...      0.5        1.94           0.0        NaN
1             7.20  ...      0.5        0.00           0.0        NaN
2            13.50  ...      0.5        5.00           0.0        NaN
3            24.70  ...      0.5        0.50           0.0        NaN
4            18.40  ...      1.5        1.00           0.0        NaN
...            ...  ...      ...         ...           ...        ...
46907        33.22  ...      0.5        0.00           0.0        NaN
46908        13.86  ...      0.5        0.77           0.0        NaN
46909        38.42  ...      0.5        1.00           0.0        NaN
46910        24.67  ...      0.5        0.00           0.0        NaN
46911        14.46  ...      0.5        3.89           0.0        NaN

       improvement_surcharge  total_amount  payment_type  trip_type  \
0                        1.0         11.64           1.0        1.0
1                        1.0          9.70           2.0        1.0
2                        1.0         21.00           1.0        1.0
3                        1.0         27.70           1.0        1.0
4                        1.0         24.65           1.0        1.0
...                      ...           ...           ...        ...
46907                    1.0         34.72           NaN        NaN
46908                    1.0         16.13           NaN        NaN
46909                    1.0         44.42           NaN        NaN
46910                    1.0         26.17           NaN        NaN
46911                    1.0         23.35           NaN        NaN

       congestion_surcharge  cbd_congestion_fee
0                      0.00                0.00
1                      0.00                0.00
2                      0.00                0.00
3                      0.00                0.00
4                      2.75                0.00
...                     ...                 ...
46907                   NaN                0.00
46908                   NaN                0.00
46909                   NaN                0.75
46910                   NaN                0.00
46911                   NaN                0.75

[46912 rows x 21 columns]>

In [34]:
print(df.columns)

Index(['VendorID', 'lpep_pickup_datetime', 'lpep_dropoff_datetime',
       'store_and_fwd_flag', 'RatecodeID', 'PULocationID', 'DOLocationID',
       'passenger_count', 'trip_distance', 'fare_amount', 'extra', 'mta_tax',
       'tip_amount', 'tolls_amount', 'ehail_fee', 'improvement_surcharge',
       'total_amount', 'payment_type', 'trip_type', 'congestion_surcharge',
       'cbd_congestion_fee'],
      dtype='object')

In [29]:
df2 = pd.read_csv('https://github.com/DataTalksClub/nyc-tlc-data/releases/download/misc/taxi_zone_lookup.csv')
df2.head()

   LocationID        Borough                     Zone service_zone
0           1            EWR           Newark Airport          EWR
1           2         Queens              Jamaica Bay    Boro Zone
2           3          Bronx  Allerton/Pelham Gardens    Boro Zone
3           4      Manhattan            Alphabet City  Yellow Zone
4           5  Staten Island            Arden Heights    Boro Zone

In [36]:
df.head(0).to_sql ( name='green_tripdata_2025-11', con=engine ,if_exists='replace')

0

In [40]:
query = 'SELECT * FROM "green_tripdata_2025-11" LIMIT 5'
pd.read_sql(query, con=engine)

Empty DataFrame
Columns: [index, VendorID, lpep_pickup_datetime, lpep_dropoff_datetime, store_and_fwd_flag, RatecodeID, PULocationID, DOLocationID, passenger_count, trip_distance, fare_amount, extra, mta_tax, tip_amount, tolls_amount, ehail_fee, improvement_surcharge, total_amount, payment_type, trip_type, congestion_surcharge, cbd_congestion_fee]
Index: []

[0 rows x 22 columns]

In [ ]:
pd.read_sql("SELECT * FROM yellow_taxi_data LIMIT 5", con=engine)

In [38]:
print(pd.io.sql.get_schema(df, name='green_tripdata_2025-11', con=engine))

CREATE TABLE "green_tripdata_2025-11" (
	"VendorID" INTEGER,
	lpep_pickup_datetime TIMESTAMP WITHOUT TIME ZONE,
	lpep_dropoff_datetime TIMESTAMP WITHOUT TIME ZONE,
	store_and_fwd_flag TEXT,
	"RatecodeID" FLOAT(53),
	"PULocationID" INTEGER,
	"DOLocationID" INTEGER,
	passenger_count FLOAT(53),
	trip_distance FLOAT(53),
	fare_amount FLOAT(53),
	extra FLOAT(53),
	mta_tax FLOAT(53),
	tip_amount FLOAT(53),
	tolls_amount FLOAT(53),
	ehail_fee FLOAT(53),
	improvement_surcharge FLOAT(53),
	total_amount FLOAT(53),
	payment_type FLOAT(53),
	trip_type FLOAT(53),
	congestion_surcharge FLOAT(53),
	cbd_congestion_fee FLOAT(53)
)

In [41]:
 df.to_sql ( name='green_tripdata_2025-11', con=engine ,if_exists='append')

912